- .travis.yml
- js/lib/function-bind.min.js
- tests/banner.tests.js
- tests/ci-tests.html
- tests/index.html
Adapted from https://github.com/wmde/fundraising/pull/715.
As for the remarks on running tests that require private key for "server-side decryption". As that part of the code is no longer in the same repository as client-side JS code, I think that those tests could be also run on CI once we have set up some kind of testing environment that tests run on CI could communicate with.
This is why I am still excluding API-related tests from CI build.
> Run QUnit tests on TravisCI

- .jshintignore
- .travis.yml
This is embarrassing to admit but the command running JSHint checks added in https://github.com/wmde/FundraisingBanners/pull/7 does not actually run any checks.
This is fixing this. Also ignoring (temporarily) sensitive banner stuff to have builds pass on Travis.
> Fix JSHint check on Travis CI

- sensitive-banner-static/res/common-banner.css
On wp.de banners are inside a `<center>` tag. Reassure text is generally left aligned.
> fix text alignment for wp.de

- .jscsrc
- .travis.yml
- js/banner/banner.api.js
- js/banner/banner.config.js
- js/banner/banner.encryption.js
- js/banner/banner.form.js
- js/banner/banner.js
- js/banner/banner.tracking.js
- js/lightbox.js
- lightbox-security.html
- tests/banner.api.tests.js
- tests/banner.form.tests.js
- tests/banner.tests.js
JSCS-related part of https://github.com/wmde/FundraisingBanners/pull/4 reloaded.
After discussion in that pull request, I suggest to comply with Mediawiki style (https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript) and use wikimedia JSCS preset (see: https://github.com/jscs-dev/node-jscs/blob/master/presets/wikimedia.json).
Only differences are that we distinguish private-like functions by prefixing them with underscores, and use non-standard "@licence" doc tag (unfortunately whole `jsDoc` block in config file must be copied from the preset in order to have all settings from there and add single custom tag).
> Add JSCS configuration and run checks on Travis CI

- sensitive-banner-static/sensitive-banner.inc.php
When anonymous donations are selected, the opt-in checkbox must be
hidden.
> Move opt-in checkbox

- js/banner/banner.api.js
Sorry, I missed this when rebasing https://github.com/wmde/FundraisingBanners/pull/8
> Fix calls to "private" methods in Banner.Api

- sensitive-banner-static/res/sensitive-banner.css
- sensitive-banner-static/sensitive-banner.inc.php
Link OWASP logo to OWASP logo on commons.
Replace static SiteSeal graphic with JS, as recommended by
https://www.globalsign.com/de-de/ssl/secure-site-seal/
Now only the icons.svg is missing.
> Replace logos

- sensitive-banner-static/res/sensitive-banner.js
- sensitive-banner-static/sensitive-banner.inc.php
As done in https://github.com/wmde/fundraising/blob/master/skin/10h16/_js/spenden.wikimedia.js#L476
Without this parameter, donation website displays empty page (with message about form not existing or so). After adding this credit card donation seem to work as on the donation site.
> Add iframe field to sensitive banner's form and used in credit card donations

- sensitive-banner-static/sensitive-banner.inc.php
Otherwise the WikiBox caching on WP.de throws annoying  errors at Masin.
AND
Now the whole content of the `#WMDE_Banner` div could be C&P to the Web:Banner page without changes.
> fixed some img scr urls & style

- js/banner/banner.form.js
The original message "Die angegebenen Daten konnten nicht in eine IBAN konvertiert werden." is a bit to long in our case.
> unified error message for invalid bank data

- sensitive-banner-static/res/sensitive-banner.js
Now double clicking on one type does not trigger the fields for the other. 
And fixes: The selected debit type is remembered on reload but the corresponding fields are there.
> sepa slider improvements

- js/banner/banner.form.js
- sensitive-banner-static/res/sensitive-banner.js
If "validated" flag of the banner js object is not reset after going back to the first-step screen, clicking the submit button sends to the form data to the donation website. As normally "SEPA confirmation" related fields are not yet checked, this results in showing empty page and storing unconfirmed direct-debit donation data.
Feel free to suggest better way of handling this.
I am also wondering why the "edit data" links ("Betrag ändern" and "Daten oder Zahlungsart ändern") do not behave like links (ie. no cursor change while hovering). Is it intended?
> Handle "edit data" links on the SEPA mandate confirmation step

- sensitive-banner-static/res/common-banner.css
cleaned and rearranged common css
addresses https://github.com/wmde/fundraising/issues/767
Note: inputs, selects and buttons don't inherit font settings from above elements. 
`#WMDE_Banner { font-family: Arial, Helvetica, Verdana, sans-serif; font-size:13px;`
has no effect on these elements. On Till's Windows PC the browser choose a default Windows font that was to big.
> fix font size and types on inputs buttons and selects

- combine_assets.php
- js/banner/banner.tracking.js
- sensitive-banner-static/sensitive-banner-js-config.template.php
When deploying on production, Piwik's URLs should be changed to those starting with "tracking.wikimedia.de".
The template intentionally uses non-existing test.wikimedia.de Piwik, as I'd rather not call the production Piwik when doing testing etc.
Tracking of the closing is currently quite redundant with this `banner.tracking` class, as it it already being done in https://github.com/wmde/FundraisingBanners/blob/master/sensitive-banner-static/res/common-banner.js#L6-L8
Piwik wouldn't count closing twice, though. But maybe it would make more sense to only use the "new" tracking class for tracking that the form has been expanded?
For testing use your own Piwik instance and change `sample`s to 1 (or more ;))
> Add tracking of closing the sensitive banner and expanding the in-banner form

- sensitive-banner-static/sensitive-banner-js-config.template.php
This just in the template, so it is not crucial. Might still be misleading, though.
> Fix URL of validation API in sensitive banner's config template

- sensitive-banner-static/res/common-banner.js
If am not mistaken this caused all banner (I mean the "normal" one and the "sensitive banner") to ignore donor selecting a recurring donation and the interval. After getting to the donation website, it is always showing "einmalig".
I've already fixed this on Central Notice. JS file should be deployed on wikipedia.de after it is merged.
> Fix checking if recurring donation has been chosen in the in-banner form

- sensitive-banner-static/res/common-banner.js
- sensitive-banner-static/res/progressbar.css
Few things that has been required while preparing https://github.com/wmde/fundraising/issues/813:
- text on the right of progress bar (remaining amount or donation goal) should not always be hidden. If it should be, and only shown after animation has finished, it should be hidden in the banner code, not in general progress bar's CSS file, I think
- text on the left side of the progress bar might also be hidden initially, and then shown after animation has finished. Change is showing it (if has been hidden)
- I tried to tweak progress bar a bit, so it does not look too small even at the beginning of the campaign.
> Progressbar improvements

- js/banner/banner.form.js
- sensitive-banner-static/res/sensitive-banner.css
- sensitive-banner-static/res/sensitive-banner.js
Display only one message.
Position the icons correctly.
Remove the spinner when really submitting the form data.
Don't linebreak error messages.
This is for https://github.com/wmde/fundraising/issues/785
> Improve error messages

- sensitive-banner-static/res/common-banner.js
- sensitive-banner-static/sensitive-banner.inc.php
Now the progress bar is at least 15% filled. If those 15% are less than
100 Pixel wide, the width is at least 100 Pixels to accomodate the text.
Use goalSum for dTarget instead of parsing a static string.
Changed banner settings to reflect data from currently running
campaigns.
This resolved the issues from https://github.com/wmde/fundraising/issues/833
> Correct lower limit on progress bar

- js/lib/jquery.cookie.js
- sensitive-banner-static/res/common-banner.js
As requested in wmde/fundraising#837, this introduces a cookie that is set when users close a banner. The cookie will be valid until the campaign ends and prevents further banners from being displayed. Using `alterImpressionData` the banner loading will not count as an impression.
To force a banner to display the cookie value has to be ignored.
Note, that this PR depends on #77.
> Hidebanner cookie

- sensitive-banner-static/res/common-banner.js
This is simply exposing current impression counts from cookies so those could be accessed in banner, e.g. for changing banner contents depending on which is the current impression for particular user (see: https://github.com/wmde/fundraising/issues/808).
> Add functions returning current banner impression counts

- js/banner/banner.tracking.js
Current code is making call to Piwik API that is using the "virtual URL" as a title of "virtual page" to track, but the tracked URL is current page.
Due to this in-banner events have not been tracked as expected (see https://github.com/wmde/fundraising/issues/892).
This sets the URL of the page to track to the virtual URL.
See also refrence of the JS Piwik client: https://developer.piwik.org/api-reference/tracking-javascript
> Fix tracking of "virtual page views" using Piwik

- js/banner/banner.form.js
- sensitive-banner-static/res/common-banner.js
- sensitive-banner-static/res/sensitive-banner.css
- sensitive-banner-static/res/sensitive-banner.js
- sensitive-banner-static/sensitive-banner.inc.php
Copied all the improvements from the DesktopBanner.js code:
- configurable cookie names
- New goal sum for 2015
Goal Sum is now configured at the top of the JS code. 
When this is merged, the fulltop banner on Wikipedia.de can use common-banner.js again and ditch DesktopBanner.js
Over time, this branch has also evolved into general fixes to make sensitive banner work on wikipedia.de
> Improve compatibility for wikipedia.de

- js/customDayName.js
As requested in https://github.com/wmde/fundraising/issues/936.
Custom date-name pairs are hard-coded in the script but I didn't come up with the way to pass such things to script that would work for both CN and wpde banners.
`getCurrentDayName` function is intended to be rather flexible, though. Its parameter might by whatever string-returning function, so the script could be (at least in theory) used for both German and English banners.
Note that things like different phrase preceding the day name, as "an diesem" or "am heutigen" in https://github.com/wmde/fundraising/issues/936 require some extra magic that is in my opinion out of the scope of this script
> Add script allowing to define custom names for particular dates

- sensitive-banner-static/res/common-banner.js
Due to the fact, that the script for https://github.com/wmde/fundraising/issues/943 counts 1 day to much, this should be changed to the 31st.
If this should affect other methods negatively we could also hack the getDaysLeft() function. Opinions?
@KaiNissen @gbirke @wmde-manicki
> set enddate to 31.12.2015

- fulltop-banner/res/fulltop-banner.css
"Real" banners have a typo in CSS files setting `poisition` of footer, which makes them display properly.
When adding lost fulltop's CSS file to the repository in https://github.com/wmde/FundraisingBanners/pull/92 I've noticed the typo and fixed it which made banner look really bad. Luckily, I haven't "fixed" that typo on Meta neither on wp.de.
> Fix position of full-top banner's footer

- fulltop-banner/res/fulltop-banner.css
see https://github.com/wmde/fundraising/issues/938
The changes differ from Peters changes. I found, that a wide broader approach is needed to let the fulltop still work good on our side. So instead of extending the rules controlling the bigger variants. I created a new rule-set for small screens in height.
> add CSS to shrink fulltop on screens with low height

- js/customDayName.js
@TillWMDE  requested to remove those two days as their does not seem to work well for viewers.
> Remove custom day names "3. Advent" and "4. Advent"

- js/common-banner.js
As required for https://github.com/wmde/fundraising/issues/991
General idea described in https://github.com/wmde/fundraising/issues/991#issuecomment-165432381 and https://github.com/wmde/fundraising-infrastructure/wiki/How-to-activate-special-banner-features#ignoring-the-banner-closed-cookie
Please note that it is already live on Meta due to BA36 being urgent
> Add a way to override the previously set "banner closed" cookie

- css/progressbar.css
Went unnoticed for quite a while. If we don't want the € to be displayed, we should remove it from the element's content rather than having it overlapped by the tip.
> fixed partly overlapped text next to pbar tip

- js/common-banner.js
Avoid having to divide by 1000000 at every step.
Prepare for language-dependent number formatting (english banners could just overwrite `formatMillion`)
> Refactor display of million euros

- js/common-banner.js
At the moment "banner closed" cookie is set to expiry by the end ot the current year. It is generally OK as long as fundraising campaigns end on Dec, 31.
But as in current campaign there will be a short "thank you" period at the beginning of 2016, and its banners will also use "banner closed" cookie, it seems to be reasonable to have a way to set custom expiry date for the cookie.
And I think it is generally good to have a way to do such things.
Note: as it creates another "parameter" that could be set in CentralNotice, this change should not be deployed into CN's `DesktopBanner.js` until current FR campaign is over. Otherwise CN will set some random value to the parameter in currently running banners, which might lead to unexpected and unwanted issues.
> Make the expiry date of the "banner closed" cookie customizable
