.gitignore, .jshintignore, .jshintrc, .travis.yml
Extracted from https://github.com/wmde/FundraisingBanners/pull/4. As that pull request requires some more work, adding just JSHint so at least some checks are run on CI.
=> Add JSHint checks and run JSHint on Travis CI

js/banner/banner.config.js, js/banner/banner.form.js, tests/banner.form.tests.js, tests/index.html
Adapted from https://github.com/wmde/fundraising/pull/723
=> Add Banner form Javascript class

sensitive-banner-static/res/sensitive-banner.js, sensitive-banner-static/sensitive-banner.inc.php
Interval and amount radio buttons now have default values.
This is especially important for the interval which is't validated on
teh server side.
=> Set form defaults for radio buttons

sensitive-banner-static/res/lightbox.css, sensitive-banner-static/res/sensitive-banner.css, sensitive-banner-static/res/sensitive-banner.js, sensitive-banner-static/sensitive-banner.inc.php
Added "data protection" as lightbox, as requested by fundraising team.
Refactored show/hide code into a generic class with event listeners to
avoid nested closeXXXBox function calls.
This closes #13
=> Refactor lightbox and add data protection

sensitive-banner-static/res/common-banner.js, sensitive-banner-static/res/sensitive-banner.js, sensitive-banner-static/sensitive-banner.inc.php
note: the missing bank-name field is added in the validation branch
=> add logic to fill data into the SEPA confirmation page

.gitignore, combine_assets.php, js/banner/banner.api.js, js/banner/banner.config.js, js/banner/banner.form.js, sensitive-banner-static/res/sensitive-banner.css, sensitive-banner-static/res/sensitive-banner.js, sensitive-banner-static/sensitive-banner-js-config.template.php, sensitive-banner-static/sensitive-banner.inc.php
Validate the form data on the server side.
Check bank data if "Lastschrift" is selected.
Validate SEPA confirmation step.
=> Banner template validation

sensitive-banner-static/res/lightbox.css
fixes https://github.com/wmde/fundraising/issues/741
=> disabled logo for "Transparente Zivilgesellschaft"

sensitive-banner-static/res/sensitive-banner.js
Following up @WMDE-Fisch's comment: https://github.com/wmde/FundraisingBanners/pull/25#issuecomment-149912293
=> Clear "send me information" checkbox after choosing anonymous donation

sensitive-banner-static/res/lightbox.css, sensitive-banner-static/sensitive-banner.inc.php
=> added bitcoin commons img url

sensitive-banner-static/res/common-banner.css, sensitive-banner-static/res/sensitive-banner.css
I miscalculated some stuff in the past. This is much better layout closer to the original and the UX design.
=> general width fixes

js/banner/banner.form.js
Error messages are now hidden when their field gets the focus.
Refactored the one-off handler for the amount into a general handler.
Put handling of validations errors of "amount" into its own function.
=> Hide error messages on focus

sensitive-banner-static/res/sensitive-banner.js
Moved click handler for SEPA page to its own, documented function.
=> Do small code cleanup

sensitive-banner-static/res/sensitive-banner.js
It could be nice if every day was 23.12 but unfortunately it its not
=> Put current date to SEPA mandate confirmation in sensitive banner

sensitive-banner-static/sensitive-banner.inc.php
minor text and link changes as seen in wmde/fundraising#756
=> minor text and link changes

.jscsrc, .jshintignore, sensitive-banner-static/res/common-banner.js, sensitive-banner-static/res/lightbox.js, sensitive-banner-static/res/sensitive-banner.js
Apply JSHint and JSCS conventions to code in sensitive-banner-static
=> Code style checks for sensitive-banner-static

sensitive-banner-static/res/sensitive-banner.css
see https://github.com/wmde/fundraising/issues/763
=> fix data policy layout

sensitive-banner-static/sensitive-banner.inc.php
this will be already deployed right now for the sensitive banner prototype on WP.org
=> changed dataprotect box text to address fundations needs

sensitive-banner-static/res/sensitive-banner.js
When the enter key is pressed in an input field, the form should be
submitted. Since we have multiple submit buttons, the first visible one
is chosen.
This is for https://github.com/wmde/fundraising/issues/759
=> Submit form on enter

sensitive-banner-static/res/sensitive-banner.js, sensitive-banner-static/sensitive-banner.inc.php
Initial value of payment type, period and amount is now tracked in
fields with the "_orig" suffix.
The code allows for empty radio buttons and pre-set radio buttons that
record the default.
This is for solving the banner side of https://github.com/wmde/fundraising/issues/775, server side was prepared in https://github.com/wmde/fundraising/pull/771
=> Track initial values

js/banner/banner.form.js
This is a solution for
https://github.com/wmde/fundraising/issues/772
=> Hide error message when user changes payment

sensitive-banner-static/sensitive-banner.inc.php
Or at least it seems to me to be a typo
=> Fix typo in SEPA mandate text

sensitive-banner-static/sensitive-banner.inc.php
This PR updates the diagram image in the lightbox "Wohin geht meine Spende", which is already changed in the banner stored on Central Notice.
=> updated diagram; server-side scaling

sensitive-banner-static/res/common-banner.css, sensitive-banner-static/sensitive-banner.inc.php
The "250 €" was breaking in IE so i had to reduce the padding a bit.
I reduced the padding on the right side, having to add it back on the
last element.
Also aligned the radio buttons for the period.
This fixes https://github.com/wmde/fundraising/issues/795
=> Fix spacing and alignment

sensitive-banner-static/res/common-banner.js
display correct values after animation is completed.
Fixed jQuery selectors
=> Refactor progress bar display

fulltop-banner/res/countCampaignDays.js
It is used e.g. in https://meta.wikimedia.org/wiki/Special:CentralNoticeBanners/edit/B15WMDE_07_151112_nthday_full
=> Add script to determine which day of the campaign it is today

js/lib/jquery.cookie.js
this plugin is used on WMF sites. we need this on wp.de to interact with cookies the same way.
=> jquery cookie plugin

fulltop-banner/res/customIntroText.js, sensitive-banner-static/res/common-banner.js
This is to handle things like https://github.com/wmde/fundraising/issues/805#issuecomment-155376608
=> Add a way to defined custom text displayed depending on the current date

js/banner/banner.form.js, sensitive-banner-static/res/common-banner.js
Moved period validation to its own function in common-banner.js
Use new function in banner.form.js
This solves https://github.com/wmde/fundraising/issues/850
=> Set period in sensitive banner

sensitive-banner-static/res/common-banner.js
this addresses wmde/fundraising#829
=> adding and removing banner space depending on interval options visibility

sensitive-banner-static/res/sensitive-banner.css, sensitive-banner-static/sensitive-banner.inc.php
Changes for issue https://github.com/wmde/fundraising/issues/851
=> Sensitive improvements

js/changeBackgroundColor.js
Simple function to make change mentioned in https://github.com/wmde/fundraising/issues/808#issuecomment-159205872 possible.
This should work by simply including the JS file and calling the function with all currently used "top banners" (including sensitive banner). For banners with different structure (e.g. "fulltop banners") ID of the HTML element that should have its background changed could be passed as a paremeter.
Side note: Directory structure in this repo seems sometimes not so wise. Feel free to suggest a better place to put this script to.
=> Add function for changing background color of the banner

sensitive-banner-static/res/common-banner.js, sensitive-banner-static/sensitive-banner.inc.php
The new function can be used instead of "animateProgressBar" on resize.
This is a prerequisite for solving wmde/fundraising#904
=> Set progress bar

sensitive-banner-static/res/common-banner.js
E.g. to have error messages in English
=> Make error messages displayed by the banner configurable

sensitive-banner-static/res/sensitive-banner.css, sensitive-banner-static/res/sensitive-banner.js
As discussed in https://github.com/wmde/fundraising/issues/893, with final design: https://github.com/wmde/fundraising/issues/893#issuecomment-159902612 and https://github.com/wmde/fundraising/issues/893#issuecomment-159910881
=> Add JS and CSS related to the "hint" in sensitive banner

sensitive-banner-static/res/common-banner.js
To handle properly changes requested for  https://github.com/wmde/fundraising/issues/816
=> Make checks that donation interval has been selected independent of form defaults

sensitive-banner-static/res/progressbar.css
Sadly we hadn't had this thing yet so the id needs to be added to the td around the bar-wrapper html.
needed for https://github.com/wmde/fundraising/issues/922
and https://github.com/wmde/fundraising/issues/923
=> adding styles for the td holding the progress bar wrapper

sensitive-banner-static/res/progressbar.css
to get a better center position
see again https://github.com/wmde/fundraising/issues/922
and https://github.com/wmde/fundraising/issues/923
P.S.: Sorry forgot about that in the other PR
=> minimize margins when using the centered progress bar

sensitive-banner-static/res/dynamic-form.css
see https://github.com/wmde/fundraising/issues/896 slightly changed CSS due to unintended effect on font size in the footer
=> added css for the dynamic form sizes on non-sensitive banners

fulltop-banner/res/fulltop-banner.css, fulltop-banner/res/mini-nag-banner.css
Those files have been part of some branches that were temporarily checked out on wikipedia.de etc but apparently got lost during the "cleaning up" process.
Copies include here are taken from files deployed on Meta. Any possible adjustments should be added if needed.
=> Add CSS files used in full-top banners

sensitive-banner-static/res/common-banner.js
Resolves https://github.com/wmde/fundraising/issues/945
Apparently the bug has been around since https://github.com/wmde/FundraisingBanners/pull/79
=> Do not submit form if no interval has been selected

sensitive-banner-static/res/common-banner.js
This introduces a way to display the remaining campaign days on English banners as well.
=> adding multilingual message generation for remaining campaign days

css/common-banner.css, js/animateHighlight.js
Those function are simply moved over from https://meta.wikimedia.org/wiki/MediaWiki:WMDE_FR2015/Resources/AnimateHighlight.js with cs things applied. Plus I added a possibility to set custom highlight colour as it turned out to be required by one of the banners on wikipedia.de (of course it has been the last one that I had to update)
=>  Add functions used to animate the highlight in the banner text 

js/customDayName.js
This PR adds custom days names in different languages (i. e. English) and resolves wmde/fundraising#1025.
=> compatibility with English language banners

js/common-banner.js
This is for https://github.com/wmde/fundraising/issues/1026
=> Add method to calculate remaining donors

css/progressbar.css
resolves wmde/fundraising#1012
To deploy, all banners using different colour schemes need to be changed as well.
=> fix display glitches on zoom

css/progressbar.css
in black / ikea banner this will be overwritten anyway
=> set default progressbar background color to orange again

css/common-banner.css
otherwise it is not be overwritten in black banners
=> set the css for the hl text less aggressive
